### ISSUE TITLE
AttributeError: 'PandaArm' object has no attribute 'move_to_cartesian_pose'

### ISSUE THREAD

**Issue by Sission** [justagist/panda_robot#11]
Franka_ros_interface v0.6.0 
Panda_robot v0.6.0

Hi! I know that the function move_to_cartesian_pose() is not in your example.
However, the panda_robot package v0.6.0 did initialized:
`franka_interface.ArmInterface.__init__(self)`
and franka_ros_interface v0.6.0 did have the function:
`def move_to_cartesian_pose(self, pos, ori=None, use_moveit=True)`

For what reason I can not call this function?

**Comment by Sission** [comment]
It turns out I used v0.6.0 instead of v0.6.0-dev for franka_ros_interface. Everything works now.
However, when I do the demo, it shows the ERROR:
JointTrajectoryActionServer: Exceeded Max Goal Velocity Threshold for panda arm

Also, the move_to_cartesian_pose() seems to have problem. It has a different orientation, which I believe you did not consider the offset between arm and hand (pi/4)

**Comment by justagist** [comment]
> However, when I do the demo, it shows the ERROR:
> JointTrajectoryActionServer: Exceeded Max Goal Velocity Threshold for panda arm

This is related to this issue: justagist/franka_panda_description#5, and is still unresolved. But you can ignore this error as long as the robot is able to move and reach the goal. This error message should not appear once this issue is fixed.
But if you really REALLY want to suppress this error message for now, you can change [this line](https://github.com/justagist/panda_simulator/blob/8e322b81180c1857c997f4efd63241ef63be19da/panda_sim_custom_action_server/src/panda_sim_custom_action_server/joint_trajectory_action_server.py#L472) in the `joint_trajectory_action_server.py` file of your `panda_simulator` repository. Change it from `return False` to `return True`. Although this should be changed back once the other issue is fixed for safety check.

> Also, the move_to_cartesian_pose() seems to have problem. It has a different orientation, which I believe you did not consider the offset between arm and hand (pi/4)

This issue is should be fixed now in commit justagist/franka_ros_interface@797feb2f57705e2b34fa7afb6b63596d6a43b5b7 of `franka_ros_interface`.

**Comment by justagist** [comment]
> > However, when I do the demo, it shows the ERROR:
> > JointTrajectoryActionServer: Exceeded Max Goal Velocity Threshold for panda arm
> 
> This is related to this issue: [justagist/franka_panda_description#5](https://github.com/justagist/franka_panda_description/issues/5), and is still unresolved. But you can ignore this error as long as the robot is able to move and reach the goal. This error message should not appear once this issue is fixed.
> But if you really REALLY want to suppress this error message for now, you can change [this line](https://github.com/justagist/panda_simulator/blob/8e322b81180c1857c997f4efd63241ef63be19da/panda_sim_custom_action_server/src/panda_sim_custom_action_server/joint_trajectory_action_server.py#L472) in the `joint_trajectory_action_server.py` file of your `panda_simulator` repository. Change it from `return False` to `return True`. Although this should be changed back once the other issue is fixed for safety check.

This issue should now be very rare. Please use the latest version of the `franka_panda_description` package.
